const statements = [
    "This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla tempora nesciunt culpa tenetur repellat veniam necessitatibus odio, expedita aliquam, neque vero id impedit quibusdam natus delectus obcaecati molestias! Eos, reprehenderit!Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla tempora nesciunt culpa tenetur repellat veniam necessitatibus odio, expedita aliquam, neque vero id impedit quibusdam natus delectus obcaecati molestias! Eos, reprehenderit!This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "This is a problem statement. How would you solve this? Implement what you have come up with Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "This is a problem statement in the doman of bla bla bla and theme of bla bla bla. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla tempora nesciunt culpa tenetur repellat veniam necessitatibus odio, expedita aliquam, neque vero id impedit quibusdam natus delectus obcaecati molestias! Eos, reprehenderit! This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "In every hackathon you get a problem statement. This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla tempora nesciunt culpa tenetur repellat veniam necessitatibus odio, expedita aliquam, neque vero id impedit quibusdam natus delectus obcaecati molestias! Eos, reprehenderit!This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
    "This is a problem statement. How would you solve this?Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem veniam veritatis impedit recusandae iure obcaecati laudantium autem aspernatur necessitatibus illo maiores earum error aliquid consectetur animi non culpa, eveniet unde nam minima cupiditate ab dolore minus blanditiis? Vero incidunt iure maiores odit asperiores et blanditiis ipsa dolorem sed illo dolore repellendus magnam maxime facilis repudiandae beatae, vel, natus debitis itaque totam tenetur, nisi ratione rerum. Magnam quaerat quis aspernatur ex fuga amet reprehenderit beatae ducimus, asperiores, nesciunt, quibusdam aut assumenda pariatur. Ea, in accusamus! Ipsam dolore qui accusantium ratione blanditiis, nisi eaque quis. Provident esse voluptate consequatur amet ipsam error, accusantium doloribus. Impedit consequatur est aliquid incidunt excepturi, tempora illum eligendi eius sunt hic, quo veritatis sint nulla quis vero repellendus! Officia amet consectetur nostrum ab eius nihil soluta totam quibusdam accusantium maxime vel nulla consequuntur quo iste minus quae corrupti commodi recusandae, repellat eaque itaque iure fuga! Iusto, voluptate.",
];

const container = document.getElementById("container");

window.onload = () => {
    statements.forEach((st, i) => {
        var div = document.createElement("div");
        div.classList.add("statement");
        if (i % 2 == 0) {
            div.classList.add("blue");
        } else {
            div.classList.add("red");
        }

        let index = i + 1;
        if (i < 9) {
            index = "0" + index;
        }
        div.innerHTML = `
        <span class="index">${i + 1}</span>
        <div class="problem">${st}</div>
        <span class="big">${index}</span>
        `;
        container.appendChild(div);
    });
};
